[package]
name = "tauri-plugin-websocket"
version = "0.0.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
exclude = ["/examples"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
http = { version = "1" }
rand = { version = "0.8" }
futures-util = "0.3"
tokio = { version = "1", features = ["net", "sync"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
